import { server } from '../config'
import Head from 'next/head'
import { GetStaticProps } from 'next'
import { ArticleList } from '../components/ArticleList'
import { articleType } from "../types/articleType"

export default function Home(props: {
  articles: articleType[]
}) {
  const articles = props.articles

  return (
    <div>

      <Head>
        <title>nextjs-crash-course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Next</h1>
      {/* {JSON.stringify(articles)} */}
      <ArticleList articles={articles} />

    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  // console.log("getStaticProps")
  const res = await fetch(`${server}/api/articles`)

  const articles = await res.json()
  console.log("articles", articles)

  return { props: { articles } };
}
